### ISSUE TITLE
CI: Investigate why CI doesn't running on PR creation

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit-sdk#158]
From [thread](https://github.com/tasitlabs/TasitSDK/pull/157#issuecomment-456995387):

@pcowgill 
> @marcelomorgado Do you agree that it appears CircleCI didn't run for this branch?

@marcelomorgado 
> It runs on my CircleCI I'm not sure but seems that always occurs on PR creation. I'll do another commit soon and then I think that it will run.

**Comment by pcowgill** [comment]
@marcelomorgado One hack to consider in the meantime is pushing the feature branch to the Tasit org's remote `tasitlabs` - I think CI always runs right away that way

**Comment by marcelomorgado** [comment]
I've just made a PR using a branch for `tasit` instead of mine and works. :+1:

**Comment by pcowgill** [comment]
Pushing feature branches to this repo works for now, and at some point we may move over to GitHub actions anyway, where the solution might be different. Closing this for now.
