### ISSUE TITLE
Merge test helpers

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit-sdk#212]
@pcowgill commented:

> I agree that now is a good moment for that. OpenZeppelin has a special repo for their test helpers, so maybe we could even make them their own child package to follow their example but with more of a monorepo style.
>
> If we do want to keep them in an existing package, we can use this question to frame it: Do the test helpers end up being used more in unit tests or integration tests? Or a little of both?
>
> If unit, maybe action. If integration, maybe tasit SDK. If mixture, probably a new child package.
>
> And I agree that some helpers functions could be utils functions exposed from the SDK. And it would be great if put comments near them about that like you mentioned.

Refs: https://github.com/tasitlabs/TasitSDK/pull/207#discussion_r258315053

**Comment by pcowgill** [comment]
This was closed by https://github.com/tasitlabs/tasit-sdk/pull/496
