### ISSUE TITLE
Use a better random number source

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit-sdk#24]
@marcelomorgado tested the ethers.js module manually following examples on docs (wallet creation, tx sign, provider calls, contract read/write functions and events). The library worked well, and the remaining issues to address are these:

1) `ethers.Wallet.createRandom()`: `WARNING: Missing strong random number source; using weak randomBytes;`
2) `ethers.Wallet.fromEncryptedJson(json, password)` / `ethers.Wallet.encrypt(password)`: [scrypt is too slow to be functional](https://docs.ethers.io/ethers.js/html/cookbook-react.html) (> 5min).

Let's determine whether these are the best packages to use to address this:
1) `react-native-secure-random-bytes` for more secure random number generation
2) `react-native-fast-crypto` makes crypto functions faster by running them on native side 

Before we go with those, we should explore alternatives in pure js and other native alternatives wrapped in a react-native package.

Note: This task is a prerequisite for https://github.com/tasitlabs/TasitSDK/issues/4

**Comment by pcowgill** [comment]
@marcelomorgado I just had a thought I wanted to run by you. As far as I understand, only these two functions from `ethers.js` are slow on React Native:

1)
```
// import wallet from encrypted json
const importedWallet = await ethers.Wallet.fromEncryptedJson(
  jsonToImport,
  password
);
```

2)
```
// export wallet to encrypted json
const jsonToExport = await fundedWallet.encrypt(password);
```

So far we've been trying to answer the question, "How can we make these functions run faster in a React Native env?"

Instead, I just wondered, "What if we can take the opinionated stance that we shouldn't need these functions at all in this SDK on mobile? And what if that somewhat counterintuitively ends up making the UX better?"

As long as the accounts generated by this SDK are only either:

(A) meant to be ephemeral and linked as additional signers to a more permanent smart-contract-based account (and then de-linked when appropriate)
or
(B) pre-authorized to create transactions involving up to certain amount of ERC20 tokens or involving only particular NFTs that are owned by another wallet

... then there's no reason ever to encrypt a "wallet" or restore a "wallet" from encrypted JSON within this SDK.

And that would mean that we can ignore the fast crypto problem in this issue and just look for a stronger source of randomness for createRandom.

What do you think?

**Comment by marcelomorgado** [comment]
You're right, I totally agree.

**Comment by marcelomorgado** [comment]
Without NodeJs.crypto, ethers.js is using Math.random (https://github.com/ethers-io/ethers.js/blob/master/shims/random-bytes.js#L7). Math.random is predictable and not safe enough:

https://www.reddit.com/r/Bitcoin/comments/2adudc/why_is_mathrandom_in_javascript_not_really_random
https://security.stackexchange.com/questions/181580/why-is-math-random-not-designed-to-be-cryptographically-secure/181623
https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba

At Expo thread about this issue (https://expo.canny.io/feature-requests/p/crypto-api), some solutions are discussed:

1. Use of linear congruential pseudo-random number generator (https://github.com/brix/crypto-js/issues/7)
This algoritmh is weak as well: https://en.wikipedia.org/wiki/Linear_congruential_generator

2. Use of expo.Accelerometer as source of entropy (https://github.com/BlueWallet/BlueWallet/blob/master/entropy.js)
Predictable range of numbers.

3. Get truly/crypto secure pseudo random number from external provider (http request) (e.g. https://www.random.org/)
Some smart contracts uses this kind of solution (https://github.com/oraclize/ethereum-examples/tree/master/solidity/random-datasource) but isn't seems a viable option from UX point of view.

4. Capture some random user input
Unviable from a UX point of view.

5. Eject and call the native crypto methods

6. Work on "ExpoRandom" PR (https://github.com/expo/expo/pull/2504)

What do you think @pcowgill ?

**Comment by pcowgill** [comment]
🎉 https://twitter.com/baconbrix/status/1096673235859431424?s=21

**Comment by pcowgill** [comment]
https://github.com/expo/expo/pull/3501

**Comment by pcowgill** [comment]
Given that it’s handled on the expo side, we’ll have to think about what parts of this task belong in the `tasit` repo

**Comment by pcowgill** [comment]
https://docs.expo.io/versions/latest/sdk/random/

**Comment by pcowgill** [comment]
Here's a version of `TweetNaCl.js` for React Native that uses expo-random as the source of randomness https://github.com/rajtatata/react-native-expo-tweet-nacl

**Comment by pcowgill** [comment]
The account package now accepts a source of randomness, and the app using the library should use a package like `expo-random` as an input. Here's an example https://github.com/tasitlabs/tasit-apps/tree/develop/apps/account-example
