### ISSUE TITLE
Make Greenkeeper uploads lockfile

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit-sdk#353]
Extracted from greenkeeper docs:

> If you use a default branch that is not master then you have to add the environment variable GK_LOCK_DEFAULT_BRANCH with the name of your default branch to your CI.

Refs: https://github.com/greenkeeperio/greenkeeper-lockfile#setup

Seems that with this config, the greenkeeper will upload the lockfile if it changes during CI test.

**Comment by pcowgill** [comment]
This is no longer relevant since we aren't using Greenkeeper anymore.
